version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-pwd
      MYSQL_DATABASE: test
      MYSQL_USER: pedro
      MYSQL_PASSWORD: pedro8745
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
